"""bake_font.py — bake Nunito Sans glyphs for the Worker's chart renderer.

    python discord/tools/bake_font.py            # writes discord/src/font.generated.js

A Worker has no canvas and no font rasteriser, and a chart without numbers on
its axes is a picture of a squiggle. So the glyphs are rendered HERE, once, and
shipped as 4-bit alpha bitmaps (~20 KB for two faces). Same reason the deck
poster's count classifier bakes its digit templates instead of rendering them
at runtime: the output must not depend on what fonts a machine has installed.

Nunito Sans is the site's own body face (SIL Open Font License), fetched from
the Google Fonts repository into a cache directory; the TTF itself is not
committed.
"""
from __future__ import annotations

import base64
import os
import pathlib
import urllib.request

from PIL import Image, ImageDraw, ImageFont

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "src" / "font.generated.js"
CACHE = pathlib.Path(os.environ.get("TEMP", "/tmp")) / "packsink-font-cache"
TTF_URL = "https://github.com/google/fonts/raw/main/ofl/nunitosans/NunitoSans%5BYTLC%2Copsz%2Cwdth%2Cwght%5D.ttf"

# Sized for an 800px-wide chart that Discord shows at ~400px: 24px renders as
# ~12px on screen, the smallest a label stays readable at.
FACES = {
    "reg": {"size": 24, "weight": 600},
    "bold": {"size": 26, "weight": 800},
}
CHARS = "".join(chr(c) for c in range(32, 127)) + "·–—…"


def ttf_path() -> pathlib.Path:
    CACHE.mkdir(parents=True, exist_ok=True)
    p = CACHE / "NunitoSans-VF.ttf"
    if not p.exists():
        urllib.request.urlretrieve(TTF_URL, p)
    return p


def bake(size: int, weight: int):
    font = ImageFont.truetype(str(ttf_path()), size)
    axes = font.get_variation_axes()
    values = []
    for ax in axes:
        name = ax["name"].decode() if isinstance(ax["name"], bytes) else ax["name"]
        values.append(weight if name == "Weight" else ax["default"])
    font.set_variation_by_axes(values)
    ascent, descent = font.getmetrics()
    glyphs = {}
    blob = bytearray()
    nibbles = []
    for ch in CHARS:
        adv = font.getlength(ch)
        x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
        w, h = max(0, x1 - x0), max(0, y1 - y0)
        offset = len(nibbles)
        if w and h:
            img = Image.new("L", (w, h), 0)
            ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
            for v in img.getdata():
                nibbles.append((v * 15 + 127) // 255)
        glyphs[ord(ch)] = [w, h, x0, y0, round(adv, 2), offset]
    if len(nibbles) % 2:
        nibbles.append(0)
    for k in range(0, len(nibbles), 2):
        blob.append((nibbles[k] << 4) | nibbles[k + 1])
    return {"size": size, "ascent": ascent, "descent": descent, "glyphs": glyphs,
            "data": base64.b64encode(bytes(blob)).decode()}


def main():
    faces = {k: bake(v["size"], v["weight"]) for k, v in FACES.items()}
    lines = [
        "// GENERATED by discord/tools/bake_font.py — do not edit.",
        "// Nunito Sans (SIL Open Font License 1.1), rendered to 4-bit alpha.",
        "// glyph: [width, height, x offset from pen, y offset from baseline, advance, nibble offset]",
        "export const FONTS = {",
    ]
    for name, f in faces.items():
        g = ",".join(f"{c}:[{','.join(str(x) for x in v)}]" for c, v in f["glyphs"].items())
        lines.append(f'  {name}: {{ size: {f["size"]}, ascent: {f["ascent"]}, descent: {f["descent"]},')
        lines.append(f"    glyphs: {{{g}}},")
        lines.append(f'    data: "{f["data"]}" }},')
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
