// extract_site.mjs — copy the site's own helpers into the Worker, verbatim.
//
//   node tools/extract_site.mjs          # writes src/site.generated.js
//
// The bot must say the same things the site says about a price: the same
// "1W" change, the same "Cheapest in 12 months", the same affiliate link, the
// same release calendar. Each of those shipped wrong at least once on the site
// before it was right, so the Worker gets a COPY of that code rather than a
// second implementation. The copy is committed (the Worker has no Index.html to
// read at runtime), and scripts/test_discord_bot.mjs fails the moment any
// copied statement no longer appears verbatim in Index.html — so a stale copy
// is a red guard, never a silent disagreement. Re-run this to refresh it.
import { writeFileSync } from "node:fs";
import { closureSource } from "./sitecode.mjs";

export const WANT = [
  // prices
  "computeSeriesDeltas", "CARD_DELTA_WINDOWS", "priceStanding",
  // links
  "tcgUrl", "tcgSetSearchUrl", "TCG_AFFILIATE_BASE", "amazonForSealed",
  // release calendar
  "SET_RELEASE_DATES", "UPCOMING_SET_NAMES", "PRODUCT_RELEASE_DATES", "CALENDAR_KINDS",
  "calendarSetEntries", "calendarEstimatedSetEntries", "calendarSetEstimates",
  "calendarProductEntries", "calendarMergeEvents", "calendarUpcoming",
  "calEventTitle", "calEventSubtitle", "calEventFullLabel", "calEstimated", "calRegionOf",
  "calTodayYmd", "calAddDays",
  // "near me": postal codes and towns, the same walk the site's event finder does
  "SC_GEO_COUNTRIES", "scPostalCandidates", "scNormalizePostal", "scZippo", "scRankPlaces",
  "scLocalTime12",
  // graded + raw eBay sales: which rollup row belongs to which printing
  "gradedSlotBucket", "rawSaleMatch",
];
// Browser-derived constants the closure would otherwise drag in. SITE_ORIGIN
// reads window.Capacitor for the native app; the bot is always the web.
const STUBS = { SITE_ORIGIN: '"https://packs.ink"' };

export function generate() {
  const { names, stmts } = closureSource(WANT, { stop: Object.keys(STUBS) });
  const head = [
    "// GENERATED by discord/tools/extract_site.mjs from Index.html — do not edit.",
    "// Each statement below is copied VERBATIM from the site; the guard test",
    "// (scripts/test_discord_bot.mjs) fails when one no longer matches. Re-run",
    "// `node discord/tools/extract_site.mjs` after changing any of them on the site.",
    "/* eslint-disable */",
    ...Object.entries(STUBS).map(([k, v]) => `const ${k} = ${v};`),
    "",
  ];
  const body = stmts.map((s) => "// ---- site ----\n" + s);
  const tail = ["", `export { ${names.sort().join(", ")} };`, ""];
  // LF throughout, whatever the checkout: the copy is compared (EOL-folded)
  // against Index.html, and a mixed-EOL file is noise in every diff.
  return (head.join("\n") + body.join("\n") + tail.join("\n")).replace(/\r\n/g, "\n");
}

if (import.meta.url === `file://${process.argv[1].replace(/\\/g, "/").replace(/^\/?/, "/")}` || process.argv[1].endsWith("extract_site.mjs")) {
  const out = new URL("../src/site.generated.js", import.meta.url);
  const src = generate();
  writeFileSync(out, src);
  console.log(`wrote ${out.pathname} (${(src.length / 1024).toFixed(1)} KB)`);
}
