// Builds dist/ — the exact set of files published to the public web.
//
// Include-list, not exclude-list. The repo root also holds ops docs, ETL
// scripts, SQL migrations, the Capacitor project and local QA harnesses. The
// Netlify `_redirects` file blocked those with `404!` lines, which is a DENY
// list: anything new added to the repo was public by default until someone
// remembered to add a rule. It had already sprung leaks — native/sync.mjs,
// package.json and capacitor.config.json were all served from packs.ink.
//
// Here the default is private. A new file is published only once it is named
// below, so forgetting to update this script fails closed instead of open.
//
// Deliberately EXCLUDED:
//   scripts/ supabase/ .github/  — ETL, migrations, CI
//   native/ android/ capacitor.config.json package*.json — build tooling
//   CLAUDE.md .mcp.json          — internal docs / agent config
//   sw-native-images.js          — native-only image SW (web uses sw.js)
//   _redirects                   — Cloudflare ignores it; worker/index.js
//                                  owns routing (see the comment there)
import { cpSync, mkdirSync, rmSync, readFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const repo = dirname(dirname(fileURLToPath(import.meta.url)));
const out = join(repo, "dist");

const FILES = [
  // Cloudflare's asset layer treats index.html as a directory index and
  // 307-redirects /Index.html → /, which leaves the capital-I file unreachable
  // and the SPA fallback serving an empty body. Publishing it lowercase is the
  // same fix native/sync.mjs applies for Capacitor's local server.
  ["Index.html", "index.html"],
  "styles.css",
  "logo.js",
  "sw.js",
  "scanner.js",
  "scanner-cv.js",
  "scanner-worker.js",
  "scanner-ocr-worker.js",
  "manifest.json",
  "privacy.html",
  // Unlisted Swiss simulator, reachable only at /lab/swiss (worker/index.js).
  "swiss.html",
  "robots.txt",
  "sitemap.xml",
  "og-image.png",
  "favicon-32.png",
  "favicon-64.png",
  "icon-192.png",
  "icon-512.png",
  "apple-touch-icon.png",
  // Cloudflare reads _headers from the assets directory, same syntax as
  // Netlify. It applies to static assets only — the image-proxy responses are
  // generated by the worker, which sets its own cache + CORS headers.
  "_headers",
];

// NOTE: these are copied from DISK, not from git — an untracked file sitting in
// one of these directories locally would be published. Hence excludeExt: the
// commissioned wordmark ships as .ai/.pdf sources next to the .png the site
// actually uses, and PacksInk.ai alone is 18.6 MB of Illustrator data.
const DIRS = [
  ["Logos", { excludeExt: [".ai", ".pdf"] }],
  ["vendor", {}],   // react/react-dom/htm/supabase/html2canvas + ort WASM
  ["scanner", {}],  // ONNX weights, admin-gated but must be fetchable
];

// Guard: the worker's proxy routes and the paths baked into Index.html + sw.js
// have to agree. The service worker caches by exact URL and the Capacitor app
// absolutizes these prefixes to packs.ink, so a rename silently breaks image
// caching on web AND every installed native build. Fail the build instead.
const indexSrc = readFileSync(join(repo, "Index.html"), "utf8");
for (const marker of ["/img-proxy", "/tcg-img-proxy"]) {
  if (!indexSrc.includes(marker)) {
    console.error(`build_dist: Index.html no longer references ${marker} — worker route is stale, refusing to build.`);
    process.exit(1);
  }
}

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });

for (const entry of FILES) {
  const [src, dst] = Array.isArray(entry) ? entry : [entry, entry];
  const from = join(repo, src);
  // Fatal, not a warning: this is the deploy artifact. A missing file here
  // ships a broken site, so it should stop the build, not print and continue.
  if (!existsSync(from)) {
    console.error(`build_dist: missing ${src} — refusing to build.`);
    process.exit(1);
  }
  cpSync(from, join(out, dst));
}

for (const [dir, opts] of DIRS) {
  const from = join(repo, dir);
  if (!existsSync(from)) {
    console.error(`build_dist: missing ${dir}/ — refusing to build.`);
    process.exit(1);
  }
  const excl = (opts.exclude || []).map((e) => join(from, e));
  const exclExt = opts.excludeExt || [];
  cpSync(from, join(out, dir), {
    recursive: true,
    filter: (src) =>
      !excl.some((e) => src === e || src.startsWith(e + "\\") || src.startsWith(e + "/")) &&
      !exclExt.some((e) => src.toLowerCase().endsWith(e)),
  });
}

let bytes = 0, count = 0, biggest = { size: 0, path: "" };
const walk = (d) => {
  for (const ent of readdirSync(d, { withFileTypes: true })) {
    const p = join(d, ent.name);
    if (ent.isDirectory()) { walk(p); continue; }
    const size = statSync(p).size;
    bytes += size; count++;
    if (size > biggest.size) biggest = { size, path: p.slice(out.length + 1) };
  }
};
walk(out);

// Cloudflare caps a single asset at 25 MiB and a project at 20,000 files.
const MAX_FILE = 25 * 1024 * 1024;
if (biggest.size > MAX_FILE) {
  console.error(`build_dist: ${biggest.path} is ${(biggest.size / 1048576).toFixed(1)} MB, over Cloudflare's 25 MiB per-asset cap.`);
  process.exit(1);
}
if (count > 20000) {
  console.error(`build_dist: ${count} files, over Cloudflare's 20,000-asset cap.`);
  process.exit(1);
}

console.log(`build_dist: ${count} files, ${(bytes / 1048576).toFixed(1)} MB → dist/`);
console.log(`build_dist: largest ${biggest.path} (${(biggest.size / 1048576).toFixed(1)} MB)`);
