"""
build_i18n.py - bake the site's language dictionaries.

    python scripts/build_i18n.py           # write i18n/<lang>.js
    python scripts/build_i18n.py --check   # fail if a .js is stale or a _t() key is missing

Inputs (all hand-edited or regenerated, all committed):
  i18n/src/ui.json              English UI string -> [ja, de, fr, it]. "" = fall back
                                to English (used for sentence fragments).
  i18n/src/terms.json           ink / rarity / type / class / set glossary per language,
                                regenerated by `sync_intl_cards.py --terms-out`.
  i18n/src/terms_overrides.json hand entries merged over terms.json.
  i18n/src/faq/<lang>.html      the How-it-works page, translated from the HTML
                                `python scripts/faq_source.py` prints. Its first
                                line is `<!-- en:<hash> -->`, the hash of the
                                English it was translated from; a different
                                current hash prints a warning (never an error:
                                the translation keeps rendering until redone).

Output: i18n/<lang>.js, one line setting window.PACKS_I18N, loaded by the
pre-paint boot in Index.html. Bump I18N_VER there whenever these change, or a
browser keeps the old dictionary until the service worker's network-first
fetch replaces it (it will, but one page view late).

--check also FAILS on a `_t("...")` key in Index.html that ui.json lacks (it
would show in English in every language). Text never wrapped in _t() at all
is caught by scripts/i18n_audit.mjs / scripts/test_i18n_coverage.mjs.
"""
from __future__ import annotations

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "i18n", "src")
OUT = os.path.join(ROOT, "i18n")
LANGS = ["ja", "de", "fr", "it"]
PLACEHOLDER = re.compile(r"\{(\w+)\}")

# Month and weekday names for the calendar (CAL_MONTHS / CAL_MONTHS_SHORT /
# CAL_DOW_SHORT in Index.html). `ym` is how a month heading reads: Japanese
# writes the year first ("2026年10月"). Short months are written out rather
# than sliced, since French juin / juillet share their first three letters.
DATES = {
    "ja": {"months": [f"{i}月" for i in range(1, 13)], "monthsShort": [f"{i}月" for i in range(1, 13)],
           "dowShort": ["日", "月", "火", "水", "木", "金", "土"], "ym": "{y}年{m}"},
    "de": {"months": ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"],
           "monthsShort": ["Jan", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"],
           "dowShort": ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"]},
    "fr": {"months": ["janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"],
           "monthsShort": ["janv.", "févr.", "mars", "avr.", "mai", "juin", "juil.", "août", "sept.", "oct.", "nov.", "déc."],
           "dowShort": ["dim.", "lun.", "mar.", "mer.", "jeu.", "ven.", "sam."]},
    "it": {"months": ["gennaio", "febbraio", "marzo", "aprile", "maggio", "giugno", "luglio", "agosto", "settembre", "ottobre", "novembre", "dicembre"],
           "monthsShort": ["gen", "feb", "mar", "apr", "mag", "giu", "lug", "ago", "set", "ott", "nov", "dic"],
           "dowShort": ["dom", "lun", "mar", "mer", "gio", "ven", "sab"]},
}


def load(name):
    with open(os.path.join(SRC, name), encoding="utf8") as f:
        return json.load(f)


FAQ_HEAD = re.compile(r"\A<!--\s*en:([0-9a-f]+)\s*-->\s*")


def load_faq(lang: str):
    p = os.path.join(SRC, "faq", f"{lang}.html")
    if not os.path.exists(p):
        return None, None
    text = open(p, encoding="utf8").read()
    m = FAQ_HEAD.match(text)
    return (text[m.end():] if m else text).strip(), (m.group(1) if m else None)


def deep_merge(a: dict, b: dict) -> dict:
    out = dict(a)
    for k, v in b.items():
        out[k] = deep_merge(out.get(k, {}), v) if isinstance(v, dict) and isinstance(out.get(k), dict) else v
    return out


def build() -> dict[str, str]:
    ui = load("ui.json")
    terms = load("terms.json")
    over = load("terms_overrides.json")
    problems = []
    files = {}
    for i, lang in enumerate(LANGS):
        d = {}
        for k, v in ui.items():
            if k.startswith("_"):
                continue
            if not isinstance(v, list) or len(v) != len(LANGS):
                problems.append(f"ui.json: {k!r} must be a list of {len(LANGS)} strings")
                continue
            tr = v[i]
            if not tr:
                continue
            if set(PLACEHOLDER.findall(k)) != set(PLACEHOLDER.findall(tr)):
                problems.append(f"{lang}: placeholders differ in {k!r} -> {tr!r}")
            d[k] = tr
        t = deep_merge(terms.get(lang, {}), {kk: vv for kk, vv in over.get(lang, {}).items()})
        payload = {"lang": lang, "ui": dict(sorted(d.items())), "terms": t, "dates": DATES[lang]}
        faq, _ = load_faq(lang)
        if faq:
            payload["faqHtml"] = faq
        files[lang] = ("/* GENERATED by scripts/build_i18n.py from i18n/src/*.json - edit those, not this. */\n"
                       "window.PACKS_I18N=" + json.dumps(payload, ensure_ascii=False, separators=(",", ":"), sort_keys=True) + ";\n")
    if problems:
        print("\n".join(problems))
        sys.exit(1)
    return files


def code_keys() -> list[str]:
    with open(os.path.join(ROOT, "Index.html"), encoding="utf-8-sig") as f:
        s = f.read()
    keys = []
    for m in re.finditer(r'\b_t(?:Rich)?\("((?:[^"\\]|\\.)*)"', s):
        k = json.loads('"' + m.group(1) + '"')
        if k not in keys:
            keys.append(k)
    return keys


def write_ui_canonical() -> None:
    """ui.json one entry per line, so a review diff shows one changed string
    as one changed line."""
    ui = load("ui.json")
    items = list(ui.items())
    lines = ["{"] + [" " + json.dumps(k, ensure_ascii=False) + ": " + json.dumps(v, ensure_ascii=False)
                     + ("," if i < len(items) - 1 else "") for i, (k, v) in enumerate(items)] + ["}"]
    text = "\n".join(lines) + "\n"
    p = os.path.join(SRC, "ui.json")
    if open(p, encoding="utf8").read() != text:
        with open(p, "w", encoding="utf8", newline="\n") as f:
            f.write(text)


def main() -> int:
    check = "--check" in sys.argv
    if not check:
        write_ui_canonical()
    files = build()
    stale = []
    for lang, text in files.items():
        p = os.path.join(OUT, f"{lang}.js")
        cur = open(p, encoding="utf8").read() if os.path.exists(p) else None
        if cur != text:
            if check:
                stale.append(p)
            else:
                with open(p, "w", encoding="utf8", newline="\n") as f:
                    f.write(text)
                print(f"wrote {os.path.relpath(p, ROOT)} ({len(text) // 1024} KB)")
    ui = load("ui.json")
    missing = [k for k in code_keys() if k not in ui and k != "English string"]
    if missing:
        print(f"{len(missing)} _t() keys have no entry in i18n/src/ui.json (they show in English):")
        for k in missing[:60]:
            print("   ", k)
    try:
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
        from faq_source import faq_hash
        cur_hash = faq_hash()
        for lang in LANGS:
            _, h = load_faq(lang)
            if h and h != cur_hash:
                print(f"note: i18n/src/faq/{lang}.html was translated from an older English FAQ "
                      f"(en:{h}, now en:{cur_hash}) - it still renders; redo it from `python scripts/faq_source.py`")
    except SystemExit as e:
        print(f"note: could not hash the English FAQ ({e})")
    if stale:
        print("STALE (run python scripts/build_i18n.py):", *stale, sep="\n  ")
        return 1
    # A _t() key with no ui.json entry ships English in every language, and
    # nothing on screen says so. Since 2026-10-03 that fails --check (and so
    # test_intl_cards.py / CI); "" in ui.json is the deliberate way to keep a
    # string English. Text never wrapped in _t() is scripts/i18n_audit.mjs's job.
    if check and missing:
        print("MISSING: add the keys above to i18n/src/ui.json (ja, de, fr, it), then run build_i18n.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
